---
title: "Resultaten"
author: "C. Schouwenaar"
date: "`r Sys.Date()`"
output: html_document
---

# Inlezen resultaten

```{r set up, include=FALSE}
library(sjlabelled)
library(tidyverse)

GemiddeldNL <- read_delim("Datasets/ErvarenGezondheid_Stress_PsychischeKlachten.csv", 
                                                          delim = ";", 
                                                          escape_double = FALSE, 
                                                          trim_ws = TRUE) %>% 
  filter(Codering_3 == "NL01" & Marges == "MW00000") %>%
  remove_all_labels()
GemiddeldNL2 <- read_delim("Datasets/50090NED_UntypedDataSet_22072024_163559.csv", 
                           delim = ";", 
                           escape_double = FALSE, 
                           trim_ws = TRUE) %>% 
  filter(Codering_3 == "NL01" & Marges == "MW00000") %>%
  remove_all_labels()
GemiddeldNL$EenOfMeerLangdurigeAandoeningen <- GemiddeldNL2$EenOfMeerLangdurigeAandoeningen_16
GemiddeldNL$BeperktVanwegeGezondheid <- GemiddeldNL2$BeperktVanwegeGezondheid_17
GemiddeldNL$ErnstigBeperktVanwegeGezondheid <- GemiddeldNL2$ErnstigBeperktVanwegeGezondheid_18
GemiddeldNL$LangdurigeZiekteEnBeperkt <- GemiddeldNL2$LangdurigeZiekteEnBeperkt_19
rm(GemiddeldNL2)

Stress <- read_csv("Results/z_scores_stress_ranked.csv")
BeperktDoorGezondheid <- read_csv("Results/z_scores_chronic_ranked.csv")
GoedeErvarenGezondheid <- read_csv("Results/z_scores_health_ranked.csv")
RisicoDepressie <- read_csv("Results/z_scores_dep_ranked.csv")

```

# Figuren

```{r}

```

